### ISSUE TITLE
my Jquery script  is not working on top of this dashboard

### ISSUE THREAD

**Issue by hijizaly** [DashboardPack/architectui-html-theme-free#10]
This dashboard is nice but the problem that when i try to write my jquery script it not work ,when i try to edit main.js file for remove your any jquery script and add another fresh from CDN 
i can't coz it  minified any solution plz

**Comment by riyazahamedr** [comment]
I am also wanted the same solution... can anyone help us plz...

**Comment by Mehonder** [comment]
1- İnsert first row to main.js,  ( $TUM change with alias)
**var $TUM= {};**

2- Find a()(document) ready function and insert this row before document ready:
**$TUM = a().noConflict( );** 
        _a()(document).ready(function () {_

3-Save main.js

4- Now avaible

	 $TUM ("#bt_kaydet").click( function () {
		 // XXXXXXXXX
        } 
		);

**Comment by DPTeamMember** [comment]
The main.js file contains all libraries and the Jquery code we are using in the template is created using webPack. It's a minified file.
This main.js file does not allow accessing libraries and the Jquery code outside the file. If you wish to edit or add js code you need to include the respective libraries like Jquery and Bootstrap in the scripts section. You can use CDN or downloaded folders for the same.
For example, in order to get the modal work, you need to include Jquery and Bootstrap in the scripts section of the HTML file.

Thank you.
