### ISSUE TITLE
Pop modal using jquery

### ISSUE THREAD

**Issue by cheefi** [DashboardPack/architectui-html-theme-free#13]
Hi, Im trying to pop up modal using bootstrap method with the code below : 

$('#id').modal('show');

and its not working at all. Are we using another function to pop up the modal?

**Comment by bhaveshbane** [comment]
TypeError: $(...).modal is not a function 
when i try to show modal

**Comment by sandinur** [comment]
Yeah, i am same ...
i can not use $('selector').modal('options'));

**Comment by phillmorgan28** [comment]
Anyone know how to fix this?

**Comment by wausin** [comment]
my solution is, add new script tag jquery after main.js

any new code please put after jquery.

yes it is bulky , but it solve my problem

**Comment by evangelos-dimitriadis** [comment]
This is actually duplicate with the https://github.com/DashboardPack/architectui-html-theme-free/issues/5
I am wondering since this is a bug, are you going to fix it for the free version?

**Comment by DPTeamMember** [comment]
The main.js file contains all libraries and the Jquery code we are using in the template is created using webPack. It's a minified file.
This main.js file does not allow accessing libraries and the Jquery code outside the file. If you wish to edit or add js code you need to include the respective libraries like Jquery and Bootstrap in the scripts section. You can use CDN or downloaded folders for the same.
For example, in order to get the modal work, you need to include Jquery and Bootstrap in the scripts section of the HTML file.

Thank you.
