### ISSUE TITLE
CSS loads after content is displayed generating layout break

### ISSUE THREAD

**Issue by dfiedlerx** [DashboardPack/architectui-html-theme-free#4]
Whenever I load a page in the template, the page content loads first with broken layout. After every page load css starts working. Is there something I'm doing wrong?

![image](https://user-images.githubusercontent.com/32338795/66788923-e2a2e000-eebf-11e9-91a5-5ada88279f9e.png)

**Comment by sublimedatasys** [comment]
Hi @dfiedlerx ,

Reasons that causing : 
CSS loading last due to slow internet 
There is conditional bundling can also affect the same. After that due to browser caching you will see the normal behaviour.
Also, as this project gives user to take maximum functionality(Plugins) advantage. There is much CSS or JavaScript loading at the top of the page which delaying.

So, In your own project make sure consider following things :
You need to configure browser caching properly
You need to enable HTTP KeepAlive (persistent connections).
Load document object model accordingly.

Thank you.

**Comment by robinmalik** [comment]
This happens to me when running locally, for about 1/2 a second or so before the css applies. The transitions are very clunky as a result, and happens everytime I click a new link. I haven't done anything I'm aware of to disable caching.
